### ISSUE TITLE
Epic Rspec Definition

### ISSUE THREAD

**Issue by nic-lan** [nic-lan/rplate#2]
A generated rspec file should include:
- [x] a describe block for each entity method with:
  - [x] the subject predefined #15
  - [ ] ~~a valid example~~

A generated rspec should not include:
- [x] a describe block related to the `initialize` method
- [ ] ~~a duplicate describe block when a method is present as class method and instance method ( e.g. `perform` and `self.perform` ). In such a case only the class method should be included.~~
